### PR TITLE
Create githubstudent.md

### LINKED ISSUE #37: Merge your branch githubstudent
- [x] Make a branch
- [x] Commit a file `githubstudent.md`
- [x] Submit a Pull Request
- [x] Get a :+1: 
- [x] Merge it

### PR DESCRIPTION
**Pull request by githubstudent**
Fixes #37

### CODE REVIEW

**Comment by markcreekmore** [comment]
:+1:

**Comment by mcable1004** [comment]
:+1: :shipit:

**Comment by ryankaplan88** [comment]
:+1:

**Comment by tudor8210j** [comment]
:trollface:

**Comment by rbanavar** [comment]
:tropical_drink:  change looks good

**Comment by ericwdavidson** [comment]
:-1:

**Comment by ALeonard9** [comment]
:ear:

**Comment by deetasaur** [comment]
:+1:

**Comment by acheng16** [comment]
Lets ask the :8ball:

**Comment by githubstudent** [comment]
:boom:

**Comment by tudor8210j** [comment]
It;s all about the :moneybag:

**Comment by deetasaur** [comment]
:scream:

**Pull request merged**
