### PR TITLE
Add these extremely vital files to the project

### PR DESCRIPTION
**Pull request by githubstudent**
### Background
- Found this bug #10 
- Fixed it!
- Tested it
### Justification

excited

:rocket: was broken

### CODE REVIEW

**Comment by githubstudent** [comment]
@githubteacher can you please review this change?

**Comment by githubstudent** [comment]
@tudor8210j maybe can you review this? @githubteacher seems busy

**Comment by tudor8210j** [comment]
Looks like very important changes that could effect the entire world and fabric of the universe....APPROVED!

**Comment by pbergstedt** [comment]
:smirk_cat:

**Comment by tudor8210j** [comment]
:neckbeard:

**Comment by pbergstedt** [comment]
- Time for Lunch !!!!

**Pull request merged**
