### PR TITLE
Create markcreekmore.txt

### LINKED ISSUE #22: Need to merge banch from markcreekmore.
This is a test issue to use for the merge.

### PR DESCRIPTION
**Pull request by markcreekmore**
Fixes #22

### CODE REVIEW

**Comment by markcreekmore** [comment]
@ericwdavidson can you review?

**Comment by markcreekmore** [comment]
@InvertedReality can you review?

**Comment by markcreekmore** [comment]
Assigned to @ryankaplan88

**Comment by markcreekmore** [comment]
@githubstudent can you review and merge?

**Comment by githubstudent** [comment]
Looks good :+1:

**Comment by ryankaplan88** [comment]
:-1:

**Comment by ryankaplan88** [comment]
:8ball:

**Pull request merged**
